### ISSUE TITLE
"MemoryError:" when trying to run it on an ESP8266 NodeMCU breakout

### ISSUE THREAD

**Issue by Thalaivar** [micropython-IMU/micropython-mpu9x50#12]
How can I get over this error?

**Comment by peterhinch** [comment]
The approach to running large modules on RAM limited devices is to use frozen bytecode. Put the MicropPython modules into `ports/esp8266/modules` in the source tree. Then rebuild the firmware and install. This causes the MicroPython code to be compiled to bytecode on the PC; on installation the bytecode is stored in Flash.

**Comment by Thalaivar** [comment]
Thanks for your reply! However I'm a newb when it comes to uPy. Till now, to install the firmware, I've been directly using esptool.py and the bin files from the micropython downloads page. How do I rebuild and install the firmware as you mentioned?

**Comment by peterhinch** [comment]
A starting point might be to read [the build document](https://github.com/micropython/micropython/blob/master/ports/esp8266/README.md).

General questions are best raised in [the forum](https://forum.micropython.org/). GitHub issues are intended for bug reports.
