### ISSUE TITLE
How fast we can read data from the sensor

### ISSUE THREAD

**Issue by nursanamar** [micropython-IMU/micropython-mpu9x50#18]
A lot of example that i saw always using the sleep function on each reading, is it possible to not using the sleep function?, and if it is necessary to use, what is the shortest time to sleep?. 

BTW, I am using mp6050 with class MPU6050 in imu.py file

**Comment by peterhinch** [comment]
The delays are largely to limit the rate at which data scrolls off the screen. The maximum rates that make sense depend on the low pass filter settings you choose. See [the docs](https://github.com/micropython-IMU/micropython-mpu9x50/blob/master/README_MPU9150.md).

**Comment by nursanamar** [comment]
Thanks for the response!

So, by making the `filter_range` lower give me a lower delay but  also increased the noise, right?

**Comment by peterhinch** [comment]
Yes. You may need to consider the effects of vibration which (depending on application) can be huge.

**Comment by nursanamar** [comment]
Thanks for your time I really appreciate it.

Closing the issue
