### ISSUE TITLE
i can't use mpu6050 by ur module as the demo.

### ISSUE THREAD

**Issue by Irvingao** [micropython-IMU/micropython-mpu9x50#19]
![图片](https://user-images.githubusercontent.com/58903762/100602918-798a6000-333f-11eb-8113-7a158ce11240.png) 
i had tested the the code:
`from imu import MPU6050

imu = MPU6050('Y')
print(imu.accel.xyz)
print(imu.gyro.xyz)
print(imu.temperature)
print(imu.accel.z)`
i connnected "X9" and "X10" for "SCL" and ""SDA".
but always :MPUException: I2C failure when communicating with IMU.
Thank you for help!

**Comment by peterhinch** [comment]
The 'Y' side I2C connection is on Y9 and Y10. See [the docs](http://micropython.org/resources/pybv11-pinout.jpg).

**Comment by Irvingao** [comment]
but i still met the same problem that" I2C failure when communicating with IMU". how can i do next?

**Comment by Irvingao** [comment]
and when it inits, i have to wait for over 30 seconds, it that too slow
?

**Comment by Irvingao** [comment]
and when it inits, i have to wait for over 30 seconds, it that too slow?

**Comment by peterhinch** [comment]
I can't explain that behaviour. Initialisation is normally immediate. I wonder if you have a genuine InvenSense chip or a Chinese clone?

**Comment by peterhinch** [comment]
Closing this. I assume it's resolved.
