### ISSUE TITLE
Error while using imu.py on Pi Pico

### ISSUE THREAD

**Issue by sahiljhawar** [micropython-IMU/micropython-mpu9x50#21]
`Traceback (most recent call last):`
`File "<stdin>", line 2, in <module>`
`File "mpu6050.py", line 84, in __init__`
`TypeError: can't convert str to int`

**Comment by peterhinch** [comment]
> File "mpu6050.py"

This repository does not contain such a file.

**Comment by sahiljhawar** [comment]
> > File "mpu6050.py"
> 
> This repository does not contain such a file.

Sorry, I opened the issue in a different repository. It was supposed to be on a different one.
