### ISSUE TITLE
imu.py: Cant convert str to int

### ISSUE THREAD

**Issue by Bugsia** [micropython-IMU/micropython-mpu9x50#22]
Hello,

I try to use the MP6050 with the Pico so I use the file "imu.py", which i renamend to "mpu6050.py" on my pico.
When I create a new object with: "mpu = MPU6050('x')" I get the error "cant convert str to int" on the 83th line.
When I the use thsi command: "mpu = MPU6050(1)". So I replace the sring with an int, I get the error: "Invalid I2C instance"
What value do I have to enter there?

**Comment by peterhinch** [comment]
See [the docs](https://github.com/micropython-IMU/micropython-mpu9x50/blob/master/README_MPU9150.md#methods). The concept of `x` and `y` sides applies only to Pyboards. For other targets you must pass an initialised I2C object.
