### ISSUE TITLE
INT pin?

### ISSUE THREAD

**Issue by ser** [micropython-IMU/micropython-mpu9x50#23]
ANy suggestions how to use this library utilising INT pin on MPU 9250?
I would like to use Motion Detection notifications - how can I receive them?
![image](https://user-images.githubusercontent.com/231537/124374874-dfb9d580-dcc8-11eb-9ce4-26d006c23fd5.png)

**Comment by peterhinch** [comment]
This is a feature I'm aware of, but have never studied for use. My applications for IMU's use asynchronous programming with **uasyncio**. In this context detecting motion is easy. Run a task which periodically compares current values with prior ones and triggers an **Event**. See [uasyncio tutorial](https://github.com/peterhinch/micropython-async/blob/master/v3/docs/TUTORIAL.md).

It rather depends on why you want to use the INT. The way which makes most sense is as a means of exiting deepsleep. The deepsleep mechanism is platform dependent, so any solution will need some research.

In any event you'll need to program the INT mechanism explicitly. I have no plans to integrate this into the driver.
