### ISSUE TITLE
Tilt Angle Question

### ISSUE THREAD

**Issue by jms547** [micropython-IMU/micropython-mpu9x50#27]
Is there any easy way to quickly obtain the tilt angle of the sensor? Or just lots of manual calculations?

I'm a little new to this stuff, so apologies if this is a dumb question...

**Comment by peterhinch** [comment]
The [fusion module](https://github.com/micropython-IMU/micropython-fusion) allows you to extract yaw, pitch and roll Euler angles from the driver. This may be what you're after.

**Comment by jms547** [comment]
Ah that's perfect, thank you!
