### ISSUE TITLE
please

### ISSUE THREAD

**Issue by circlezk** [micropython-IMU/micropython-mpu9x50#28]
Traceback (most recent call last):
  File "<stdin>", line 22, in <module>
  File "mpu9250.py", line 19, in __init__   
  File "imu.py", line 174, in __init__      
TypeError: can't convert str to int

**Comment by peterhinch** [comment]
The line numbers in your traceback do not match the published code. See, for example, [mpu9250.py line 19](https://github.com/micropython-IMU/micropython-mpu9x50/blob/f35a9036e280972b0fc0f344ce05b0b0c6abfdc2/mpu9250.py#L19) which is part of the licence text.

Please ensure you are running the published code.

**Comment by peterhinch** [comment]
Closed due to inactivity.
