### ISSUE TITLE
MPU9255 support?

### ISSUE THREAD

**Issue by SalimTerryLi** [micropython-IMU/micropython-mpu9x50#3]
Excuse me,have you test whether it would work on MPU9255 or not?sry4my poor English...

**Comment by peterhinch** [comment]
There is a driver for the MPU9250 but I haven't yet studied the MPU9255.

**Comment by SalimTerryLi** [comment]
Thanks. MPU9255&9250 have almost the same documents (both in hardware description and I2C Timing Characteristics). So I' ll try it some days later.Wish it could work!

**Comment by peterhinch** [comment]
Please report your results here.

**Comment by SalimTerryLi** [comment]
I'm sorry I use RAPI too. So there is nothing I can help to do.
