### ISSUE TITLE
Correct breakoutboard?

### ISSUE THREAD

**Issue by manuschiller** [micropython-IMU/micropython-mpu9x50#6]
Hi!
the link to drotek for the breakout board is down..

Is this the correct breakout board for your driver?
https://www.amazon.com/Mpu-9250-Nine-axis-Attitude-Acceleration-Magnetic/dp/B00OPNUO9U/ref=sr_1_1?ie=UTF8&qid=1490347200&sr=8-1&keywords=mpu9250

thanks!

**Comment by peterhinch** [comment]
I haven't seen that board before but I'd expect it to be OK. [This link](https://drotek.com/shop/en/drotek-parts/421-mpu9250-gyro-accelerometer-magnetometer.html) to Drotek worked for me.
